### ISSUE TITLE
Running tests behat under 5.3

### ISSUE THREAD

**Issue by tyx** [rezzza/rest-api-behat-extension#1]
For now we use `php -S`. Need to use a real apache for 5.3...

**Comment by shouze** [comment]
Do we still care?

**Comment by tyx** [comment]
well, if we want to continue to support 5.3 it would be great to run tests over this version.

And I don't see any good reason to stop supporting 5.3

**Comment by shouze** [comment]
I have one: php 5.3 is officially deprecated in fact. As php 7 is coming looks like it should be a better option to have php 5.4 as a minimum requirement.

**Comment by stephpy** [comment]
+1 for @tyx, 5.3 is still used (the most used) and there is no reason to stop supporting 5.3.

We don't use traits, yields, etc... And keeping `array` ATM is not a problem to me.

**Comment by shouze** [comment]
behat still support >=5.3.3...

Let's talk about real numbers:
http://w3techs.com/technologies/details/pl-php/5/all

Still 38% of php 5.x market share yup... but it's a global market share number for php 5.x releases.
How many people really using behat for bdd tests still use php 5.3 nowaday?

**Comment by stephpy** [comment]
This is not the question. Why should we drop support ? Using `[]` instead of `array()` ?
If our code conception makes us use `>5.3 ` functionnality, why not. It's not the case ATM.

**Comment by shouze** [comment]
Dropping 5.3 support is just a question of energy. Here we should need to upgrade our .travis.yml to use apache or nginx with a vhost.
So ok why not but if we do that I think it's a good thing to create a milestone with other things that `php -S` don't support no? (I thinkg about the HTTP `LINK` method ATM).

**Comment by stephpy** [comment]
:+1:

**Comment by tyx** [comment]
php 5.3 will be remove from requirements in #52

**Comment by shouze** [comment]
and php 5.3 is deprecated BTW
