### ISSUE TITLE
V3 => Leave Guzzle

### ISSUE THREAD

**Issue by tyx** [rezzza/rest-api-behat-extension#18]
Need to leave the requirement to Guzzle by moving to PSR7 interfaces ?

* Use https://github.com/php-http ?

**Comment by shouze** [comment]
should be cool indeed :+1:

**Comment by dsamblas** [comment]
If no one has take this one yet I would love to give a try

**Comment by tyx** [comment]
It would be great !

Currently on others projects we use https://github.com/egeloen/ivory-http-adapter

It works great and support Guzzle in all versions.

**Comment by dsamblas** [comment]
Wops.. obsolete again :P let's go for it's replacement  https://github.com/php-http instead?

**Comment by tyx** [comment]
Things are definitively going too fast in this world...

Yes of course, let's use this new initiative !

**Comment by dsamblas** [comment]
At the end I choose the "deprecated" one.
php-http project stills in very early stages get, I will keep an eye, and  implement it when they are more mature,ivory-http-adapter is quite complete and tested to still being a valid chose,  when it becomes a real alternative I will replace the lib.

first working approach to review and comment
https://github.com/rezzza/rest-api-behat-extension/pull/28
(unit tests pending)

**Comment by dsamblas** [comment]
units test working an some of your comments done :)
https://github.com/rezzza/rest-api-behat-extension/pull/28

**Comment by tyx** [comment]
Nice ! So only configuration via options is missing, I will have a look if I can help on this subject.

**Comment by dsamblas** [comment]
Ok finally I have some time to look at the  options thing ;P , first thing I realize is that there is no step using it, and RestApiBrower  just forwards it to the Guzzle3 client without adding anything, so the conclusion is that (at least in this code) we are not loosing anything removing it .

Supposing we use the  browser independently of the RestApiContext , the the $options array is really coupled to Guzzle3/Curl options, and egeolen/http-adapter only expose the following to be altered on the request through  the Configuration:
* ProtocolVersion
* KeepAlive
* EncodingType
* Boundary
* Timeout
* UserAgent

and I'm not sure if we can change on the fly (and if there is any good reason for that) the 
* BaseUri

If you agree, I can make:
* a step like **"Given I add :option option equal to :value"**
* another one 
**"Given I add this options:"**
|option | value |
to define a bunch of options at once
* and modify whatever has to be modified to pass this to the RestApiBrowser and add/modify any test to be sure this is working and no break anything :P 

So this way (at least under the point of view of the RestApiContext) we will not just not loosing functionality we will for sure gain some :) 

Or take the easy path and just forget options, and done XD
Just tell me and I will do  (or not)

**Comment by tyx** [comment]
Hi !

Yes, it's not simple. We have a use case where we disabled the forward redirect for example. I guess we will need to find another way to achieve that on our side.

Let's move on and merge this stuff !

**Comment by dsamblas** [comment]
Default egeloen/ivory-http-adapter behaviour is to disable forward on all his adapters, to enable and config redirect forwarding you should hook  to  the [redirect event](https://github.com/egeloen/ivory-http-adapter/blob/93a641e6a9f2e6ae190f1165e8886cd4824872cc/doc/events.md#redirect) , I think  is feasible make a step **"Given I allow :hoops redirect hoops"** or similar to enable it when needed

**Comment by tyx** [comment]
Thanks you @dsamblas for your great work on this one !
