### ISSUE TITLE
Allow to configure httpClient distinctly ?

### ISSUE THREAD

**Issue by tyx** [rezzza/rest-api-behat-extension#22]
Currently we cannot use RestApiBrowser on 2 different baseUrl and/or config

**Comment by shouze** [comment]
:+1:

**Comment by shouze** [comment]
@tyx ok but before or after https://github.com/rezzza/rest-api-behat-extension/issues/18 ?

**Comment by tyx** [comment]
Not important I think

**Comment by tyx** [comment]
No longer valid
