### ISSUE TITLE
Guzzle versión deprecated.

### ISSUE THREAD

**Issue by bruli** [rezzza/rest-api-behat-extension#25]
Hi.

When composer runs: 

Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by tyx** [comment]
Hi,

Yes, we are definitively aware about that but it is not easy for us to update as internally we have many and many dependencies on guzzle/http again.

But we will update one day ;)

**Comment by tyx** [comment]
You can now use [3.0.0](https://github.com/rezzza/rest-api-behat-extension/releases/tag/3.0.0) and choose your favorite http adapter ;)
