### ISSUE TITLE
Fix some ivory-http-adapter adoption edge cases

### ISSUE THREAD

**Issue by shouze** [rezzza/rest-api-behat-extension#35]
More details in live code comments from https://github.com/rezzza/rest-api-behat-extension/pull/29#discussion_r47421827

- [ ] Add some more unit tests for `RestApiBrowser::sendRequest('POST', $url, $body)` into [/tests/Units/Rest/RestApiBrowser.php](https://github.com/rezzza/rest-api-behat-extension/blob/b68af792f0f0935f145b788f8f27398df87b1c61/tests/Units/Rest/RestApiBrowser.php) with `$body` as either:
  - [ ] a string
  - [ ] an array
  - [ ] a resource
- [ ] Fix the bugs.

**Comment by tyx** [comment]
https://github.com/rezzza/rest-api-behat-extension/pull/29#discussion_r47429980

**Comment by tyx** [comment]
No longer supported since #52
