### ISSUE TITLE
Can the remove request header be public?

### ISSUE THREAD

**Issue by lfbn** [rezzza/rest-api-behat-extension#46]
Hi,

In the RestApiBrowser the removeRequestHeader is private. Can this method be public? Is private because some specific reason?

Thanks.

**Comment by tyx** [comment]
What is your usecase ? Currently this method is only internal because there is no usecase to expose it.

**Comment by lfbn** [comment]
I have a very special case. To authenticate you have to request a token. After that all the requests should have that token in the headers. To logout we should send a request with the token in the URL. I want to remove from the headers the token.

Is a very special use case, you can close the issue. I'm not sure that if there are other relevant use cases.

**Comment by tyx** [comment]
I guess an empty value should work also no ?

But for this kind od edge case I think you could directly use the `getRequest()` to perform all the stuff you need on the request.
