### ISSUE TITLE
When behat runs with verbosity, we should display response when we get the errors

### ISSUE THREAD

**Issue by tyx** [rezzza/rest-api-behat-extension#47]
When you have an error, you will (always?) need to add a `print response` to understand why you have this error and read the payload you get.
So we should try to add directly this info when you run behat with `-v` instead of displaying stack trace.

Like Mink does: https://github.com/minkphp/Mink/blob/d2c32350b42a4d4713e107bcc3fb4a4bd525fdb3/src/Exception/ExpectationException.php#L61

**Comment by stephpy** [comment]
:+1:
