### ISSUE TITLE
Upgrade to Tolerance 0.3.3

### ISSUE THREAD

**Issue by tyx** [rezzza/rest-api-behat-extension#55]
* [ ] Uncomment https://github.com/rezzza/rest-api-behat-extension/blob/master/src/Tolerance/ExecutionTimeLimited.php#L44
* [ ] Move runner execution into RestApiBrowser construct ? https://github.com/rezzza/rest-api-behat-extension/blob/master/src/Rest/RestApiBrowser.php#L112

**Comment by sroze** [comment]
Worth PRing the ExecutionTimeLimited waiter too! :)

**Comment by tyx** [comment]
I guess we can do that ;) PR is coming

**Comment by tyx** [comment]
done in #57
