### ISSUE TITLE
Update justinrainbow/json-schema

### ISSUE THREAD

**Issue by tyx** [rezzza/rest-api-behat-extension#68]
https://github.com/justinrainbow/json-schema/releases/tag/4.1.0

**Comment by shouze** [comment]
ok, nothing huge but yes we have to update at some time.

**Comment by stephpy** [comment]
Is it still BC with our usage and 2.x ? If yes, we would just have to add `>=2.0` in our composer.json

**Comment by tyx** [comment]
Yes of course, I mean allow to use newer version but 2.0 still does the job ;)

**Comment by stephpy** [comment]
👍
