### ISSUE TITLE
How to configure HTTP client ?

### ISSUE THREAD

**Issue by marmotz** [rezzza/rest-api-behat-extension#71]
I need to disable SSl check on localhost.

How to configure HTTP client used by this extension ?

**Comment by stephpy** [comment]
RestApiBrowser:: useHttpClient

Allows you to override the http client.

May be we could add a getter `getClient` in this class. ping @tyx aka the getter killer. 🍻

**Comment by tyx** [comment]
`RestApiBrowser::useHttpClient` was added in this purpose !

**Comment by marmotz** [comment]
No, I don't want to use my own http client, I want to configure the current one. 

And why use only private properties? We can't do anything after extend your class!

**Comment by tyx** [comment]
> No, I don't want to use my own http client, I want to configure the current one.
So we wait for your PR !

> And why use only private properties? We can't do anything after extend your class!
Which class ? You should not have to extend any class.

**Comment by marmotz** [comment]
> So we wait for your PR !

A PR to add a getter ? You're kidding me ? :joy: 

> Which class ? You should not have to extend any class.

RestApiBrowser class is not a final class, so I can extend it :)
In fact, I do not extend this class. It was just another solution to meet my need.
I can not retrieve the client, nor configure it, nor modify it by extending the class.

Yes I can use `RestApiBrowser::useHttpClient` but it would be like having to change a car's engine instead of changing gear.
I only want to tweak the current client.

**Comment by tyx** [comment]
>  I only want to tweak the current client.

You cannot. `php-http` does not allow to change the options of client already instantiated. 

You can just make a PR  to create the httpClient with your own set of options, it is the only change that could fit your need but it is not an easy job. This is why we added only `useHttpClient` for now.
