### ISSUE TITLE
Branch alias is out of sync with released version numbers.

### ISSUE THREAD

**Issue by bangpound** [rezzza/rest-api-behat-extension#79]
The branch alias in `composer.json` says that `dev-master` is `4.0.x-dev` but this project has a release for version 6.1.0 that is based on the master branch.

When the branch alias is not maintained, it's not possible to track the master branch while also depending on projects that require the latest version (6.x) of this one.

Should the branch alias be `6.2.x-dev` or `6.x-dev`?

**Comment by shouze** [comment]
Yes you're right... should be updated, I'm ok to merge your PR in few minutes.

**Comment by shouze** [comment]
BTW thank you again for your contributions!
