### ISSUE TITLE
Using regular expressions in JSON result testing

### ISSUE THREAD

**Issue by bystro** [rezzza/rest-api-behat-extension#81]
Assume I test a JSON in the following way ...
```
And the JSON should be equal to:
"""
      {
          "success": true,
          "products": [
              {
                  "id":"1",
                  "name":"Milk"
              },
              {
                  "id":"2",
                  "name":"Bread"
              }              
          ]
      }
      """
```

I'd like to test it using regular expressions like bellow
```
And the JSON should be equal to:
"""
      {
          "success": true,
          "products": [
              {
                  "id":"[\d]+",
                  "name":"[\w]+"
              },
              {
                  "id":"[\d]+",
                  "name":"[\w]+"
              }              
          ]
      }
      """
```

Is it possible?

**Comment by shouze** [comment]
@bystro no, as you can see in the implementation:
https://github.com/rezzza/rest-api-behat-extension/blob/5ca62bf4fb68d6e7ef1ffd7acbd8600b3671baf8/src/Json/JsonContext.php#L177-L193

But... you can use one of the other expressions based steps:
https://github.com/rezzza/rest-api-behat-extension/blob/5ca62bf4fb68d6e7ef1ffd7acbd8600b3671baf8/src/Json/JsonContext.php#L195-L230

Those expressions are based on the powerful http://jmespath.org/

Also, for what you want to do if you only want to validate a json, json schema is your friend, you can write a json schema and validate the payload against it.
You can even use https://jsonschema.net/#/editor for example to quickly interpolate a payload into a first json schema draft that you will refine.

**Comment by shouze** [comment]
Closing this issue unless I didn't answered correctly to you question 👼
