### ISSUE TITLE
And the JSON node "success" should be equal to "false" support ?

### ISSUE THREAD

**Issue by bystro** [rezzza/rest-api-behat-extension#83]
Does extension supports "false"?
When I compare boolean Json node value to "false" I get
boolean(false) is not equal to string(5) 'false'

![image](https://user-images.githubusercontent.com/14996446/32724245-c5c458aa-c870-11e7-8e71-df858bfb7b73.png)

**Comment by tyx** [comment]
Hello,

good catch ! 

In fact we should be able to write:
`And the JSON node "success" should be equal to false` 

If you have time, it's not a big deal to make the change. Otherwise I will have a look soon ;)

**Comment by stephpy** [comment]
We could reserve some words like “false|true|null" in my opinion.
